import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readKhoraPin } from "./scripts/khora-pin.mjs";
import { sidecarEmbedPlugin } from "./scripts/sidecar-embed.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	define: {
		// Injected from sidecar/pyproject.toml so the plugin's staleness gate
		// (uv.ts) and the installed dependency can never disagree. Throws — and
		// fails the build — if the pin can't be parsed.
		__KHORA_VERSION__: JSON.stringify(readKhoraPin()),
	},
	// Embeds the Python sidecar source into main.js (virtual:sidecar-files) —
	// community-directory installs receive only main.js/manifest.json/styles.css,
	// so the sidecar must travel inside the bundle.
	plugins: [sidecarEmbedPlugin()],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
